version: '3'
services:
  todoback:
    build: back-end/
    restart: on-failure
    ports:
      - 3001:3001
  todotests:
    build: tests/
    restart: on-failure
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  todofront:
    build: front-end/
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback